### ISSUE TITLE
Can't see some text on the notices (see attachment)

### ISSUE THREAD

**Issue by isums** [Nulkem/betterseqta#14]
When checking Notices you can't see some of the font, it's the same colour as the background.
<img width="541" alt="Screen Shot 2022-08-24 at 17 53 00" src="https://user-images.githubusercontent.com/78246099/186389532-61ff65ec-166f-4c6e-bf17-1044b20f64a4.png">

**Comment by Nulkem** [comment]
I have added a threshold for the text colour to fix this issue. Will be available in v2.0.5 when it releases.
