### ISSUE TITLE
[Feature] Developer API to fetch the timetable for use outside of the browser

### ISSUE THREAD

**Issue by PiemanAU** [Nulkem/betterseqta#16]
I want a developer API to fetch the timetable for use outside of the browser for other programs etc

**Comment by Nulkem** [comment]
This is not planned, as I am not associated with SEQTA or Education Horizons, doing this would potentially be seen as a security concern, which could be met with hostile action. BetterSEQTA uses internal fetch requests to SEQTA's servers through SEQTA's site, and creating an API would be done on an external site which would also require student login information or a session id and would not be officially supported by SEQTA.
