### ISSUE TITLE
Home page doesnt show First period Class

### ISSUE THREAD

**Issue by AliKamalddin** [Nulkem/betterseqta#7]
this issue is prevalent in everyone ive talked to so far, very strange. could be a school specific issue for all i know but still is annoying
![image](https://user-images.githubusercontent.com/108277937/175944847-fe258c90-e3cd-4461-8c33-8c4e307108e0.png)

![image](https://user-images.githubusercontent.com/108277937/175944991-821fdbd2-208a-41d2-9f29-03df58e9791c.png)

**Comment by Nulkem** [comment]
Fixed in the development branch and will be pushed to v2.0 which will be released soon.
